name: Daily Report Scan
on:
  schedule:
    - cron: '0 1 * * *' # Her sabah TR saatiyle 04:00 (UTC 01:00)
  workflow_dispatch: # Telefondan elle çalıştırmak istersen buton çıkarır

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          pip uninstall fpdf -y
          pip install google-generativeai fpdf2 feedparser newspaper3k lxml_html_clean
      - name: Run Script
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python haber_asistani.py
